### ISSUE TITLE
How to run serverside app after bundling

### ISSUE THREAD

**Issue by najtin** [tom-james-watson/p2p.chat#13]
`npm start ` runs the app with webpack-dev-server. 
There is the option to bundle the software. 
So i figured there must be a way to run the server side app after bundling, otherwise i don't understand what the bundle option is there for. 
I would be thankful if someone could explain it.

**Comment by najtin** [comment]
If i deplay the bundle (index.html dist/ img/) i get the following error:
![grafik](https://user-images.githubusercontent.com/42641080/77186666-888ff180-6ad3-11ea-98b4-f22297e9cf26.png)
Which does make sense, since it is just a static webpage.

**Comment by tom-james-watson** [comment]
Bundling is to produce static site files. The idea is to then serve the static site from something like netlify. The peer matching is done via a signal hub server which can be configured in the code.

I'm afraid to say that at this point the app is not being developed and is broken due to changes in browser APIs. I recommend looking elsewhere for now. I recommend meet.jit.si for an open source alternative.
